### PR TITLE
Update gateway dashboard

### PR DESCRIPTION
**Pull request by rlecomte**

### CODE REVIEW

**Review by qboileau — APPROVED** [review]

**Review by qboileau — CHANGES_REQUESTED** [review]
Need to increment the chart version too

**Comment by rlecomte** [comment]
> Need to increment the chart version too

waiting for @fteychene about this

**Comment by fteychene** [comment]
Was waiting for a version where this change should be added. 
It's going to go in 3.0.0 so changing the base branch for the 3.0.0 release branch

**Comment by fteychene** [comment]
Damn this version check is annoying ...

**Review by qboileau — APPROVED** [review]

**Pull request merged**
