### PR TITLE
feat(metrics): allow `ServiceMonitor` extra parameters setting for console

### LINKED ISSUE #60: Prometheus `ServiceMonitor` resource configuration
## Problem detail

Not possible to properly configure the `ServiceMonitor` resource, for example to configure authentication method.

## Expected behavior

Provide the possibility to add extra parameters in the `spec.endpoints[0]` section.

### PR DESCRIPTION
**Pull request by pchanvallon**
## Context

Provide the possibility to add extra parameters in the spec.endpoints[0] section in order to properly configure the `ServiceMonitor` resource, for example to configure authentication method.

## Related issues

Fixes #60

### CODE REVIEW

**Comment by qboileau** [comment]
Hi @pchanvallon, many thanks for your contribution ! 

Could you split the PR in two PR, one for Console chart and one for Gateway chart. 
Also, the one for Gateway need to have target branch set to `release/gateway/3.0.0` without chart version update (we will release it soon). 
The one for Console could still target `main` branch, but need a chart version increment to `1.6.2`.

If you don't have the time to do it, we will integrate your change on future chart releases.

Sorry for the inconvenience, but unfortunately because of our current CI setup, all commits on main branch trigger a release of the charts. So PRs that are targeting main branch need chart version to be incremented. 
We will improve that in future to reduce frictions on contributions :)

**Comment by pchanvallon** [comment]
Hello @qboileau,
Ok no problem I'll do it : will keep this one for the console, and will create another one for the gateway.

**Review by qboileau — APPROVED** [review]

**Comment by pchanvallon** [comment]
Hello @qboileau, this PR has been rebased.

**Comment by qboileau** [comment]
Good to go :heavy_check_mark: , the CI throw error because of secrets that are inaccessible from fork pull request but that's not your fault.

Thanks again for your contribution :slightly_smiling_face: and sorry for the impractical CI configuration.

**Pull request merged**
